//! Syscalls that no phase may ever admit; the tests prove none appears in the policy table.
//!
//! The list is the documented denial surface from the jail profile: socket creation,
//! `execve`, filesystem mutation, credential changes, `ptrace`, mounts, namespaces, module
//! loading, keyrings, BPF, perf, fanotify, inotify, `userfaultfd`, `io_uring`, `memfd`, and
//! every `pidfd` operation.

/// `(name, x86_64 number)` pairs that must be killed in every phase.
pub const NEVER_ALLOWED: &[(&str, u32)] = &[
    ("access", 21),
    ("shmget", 29),
    ("shmat", 30),
    ("dup", 32),
    ("dup2", 33),
    ("sendfile", 40),
    ("socket", 41),
    ("connect", 42),
    ("accept", 43),
    ("bind", 49),
    ("listen", 50),
    ("fork", 57),
    ("vfork", 58),
    ("execve", 59),
    ("wait4", 61),
    ("kill", 62),
    ("uname", 63),
    ("semget", 64),
    ("msgget", 68),
    ("getcwd", 79),
    ("chdir", 80),
    ("fchdir", 81),
    ("rename", 82),
    ("mkdir", 83),
    ("creat", 85),
    ("unlink", 87),
    ("symlink", 88),
    ("readlink", 89),
    ("chmod", 90),
    ("chown", 92),
    ("ptrace", 101),
    ("syslog", 103),
    ("setuid", 105),
    ("setgid", 106),
    ("setpgid", 109),
    ("setsid", 112),
    ("setgroups", 116),
    ("setresuid", 117),
    ("setresgid", 119),
    ("capset", 126),
    ("mknod", 133),
    ("personality", 135),
    ("pivot_root", 155),
    ("chroot", 161),
    ("mount", 165),
    ("umount2", 166),
    ("reboot", 169),
    ("sethostname", 170),
    ("init_module", 175),
    ("sched_setaffinity", 203),
    ("kexec_load", 246),
    ("waitid", 247),
    ("add_key", 248),
    ("keyctl", 250),
    ("unshare", 272),
    ("splice", 275),
    ("accept4", 288),
    ("dup3", 292),
    ("inotify_init1", 294),
    ("perf_event_open", 298),
    ("fanotify_init", 300),
    ("name_to_handle_at", 303),
    ("open_by_handle_at", 304),
    ("setns", 308),
    ("process_vm_readv", 310),
    ("process_vm_writev", 311),
    ("kcmp", 312),
    ("finit_module", 313),
    ("memfd_create", 319),
    ("bpf", 321),
    ("userfaultfd", 323),
    ("pidfd_send_signal", 424),
    ("io_uring_setup", 425),
    ("open_tree", 428),
    ("move_mount", 429),
    ("fsopen", 430),
    ("fsmount", 432),
    ("pidfd_open", 434),
    ("close_range", 436),
    ("openat2", 437),
    ("pidfd_getfd", 438),
    ("mount_setattr", 442),
    ("landlock_create_ruleset", 444),
];
